[build]
  command = "echo 'no build script'"
  publish = "public"

[[redirects]]
  from = "/1.Portfolio/index.html"
  to = "/1.Portfolio/index.html"
  status = 200

[[redirects]]
  from = "/2.ProjectNotes/1.HTMLandCSSnotes/a1ResumeAll.html"
  to = "/2.ProjectNotes/1.HTMLandCSSnotes/a1ResumeAll.html"
  status = 200
