[build]
  command = "echo 'no build script'"
  publish = "public/1.Portfolio"

[[redirects]]
  from = "/a1ResumeAll.html"
  to = "/2.ProjectNotes/1.HTMLandCSSnotes/a1ResumeAll.html"
  status = 404
  force = true