[build]
  publish = "portfolio/public" #It means: Publish directory (public/index repository)
  command = "echo 'no build script'" # It means: Build command

[[redirects]]
  from = "projects/1.ProjectNotes/*" # from = link (from é o link)
  to = "projects/1.ProjectNotes/:splat" # to = path (to é o path)
  status = 200
  force = true

[[redirects]]
  from = "projects/2.Projects/*"
  to = "projects/2.Projects/:splat"
  status = 200
  force = true
