[build]
  command = "echo 'no build script'"
  publish = "public/1.Portfolio"

[[redirects]]
  from = "public/1.Portfolio"
  to = "public/2.ProjectNotes/1.HTMLandCSSnotes/:splat"
  status = 301
