[build]
  command = "echo 'no build script'"
  publish = "public/1.Portfolio"

[[redirects]]
  from = "/1.Portfolio/2.ProjectNotes/1.HTMLandCSSnotes"
  to = "/a1ResumeAll.html"
  status = 200
