[build]
  publish = "portfolio/public" #It means: Publish directory (public/index repository)
  command = "echo 'no build script'" # It means: Build command

[[redirects]]
  from = "./../../projects/1.ProjectNotes/*"
  to = "./../../projects/1.ProjectNotes/:splat"
  status = 200
  force = true
