[build]
  publish = "./portfolio/public"
  command = "npm run build"

[[redirects]]
  from = "/a1ResumeAll"
  to = "/projects/1.ProjectNotes/1.HTMLandCSSnotes/a1ResumeAll.html"
  status = 200

[[redirects]]
  from = "/react-library"
  to = "/projects/1.ProjectNotes/3.LearningReactJS/react-library/public/index.html"
  status = 200

[[redirects]]
  from = "/learning-bootstrap"
  to = "/projects/1.ProjectNotes/4.LearningBootstrap/index.html"
  status = 200