[build]
  command = "echo 'no build script'"
  publish = "public/1.Portfolio"

[[redirects]]
  from = "../2.ProjectNotes/1.HTMLandCSSnotes/*"
  to = "../2.ProjectNotes/1.HTMLandCSSnotes/:splat"
  status = 200
