[build]
  publish = "."
  command = "echo 'no build script'"

[[redirects]]
  from = "/1.ProjectNotes/*" # from = link (from é o link)
  to = "/1.ProjectNotes/:splat" # to = path (to é o path)
  status = 200
  force = true

[[redirects]]
  from = "/2.Projects/*"
  to = "/2.Projects/:splat"
  status = 200
  force = true

[submodule "public/1.ProjectNotes/3.LearningReact.JS"]
    path = public/1.ProjectNotes/3.LearningReact.JS
    url = https://github.com/OJKSAGASFHGIK/.._Learning-React.JS