[build]
  publish = "."
  command = "echo 'no build script'"

[[redirects]]
  from = "/1.ProjectNotes/*" # from = link (from é o link)
  to = "/1.ProjectNotes/:splat" # to = path (to é o path)
  status = 200
  force = true

[[redirects]]
  from = "/2.Projects/*"
  to = "/2.Projects/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/1.ProjectNotes/3.LearningReact.JS/*" # from = link (from é o link)
  to = "/1.ProjectNotes/3.LearningReact.JS/:splat" # to = path (to é o path)
  status = 200
  force = true