[build]
  publish = "."
  command = "echo 'no build script'"

[[redirects]]
  from = "public/*"
  to = "public/1.Portfolio/:splat"
  status = 200

[[redirects]]
  from = "public/*"
  to = "public/2.ProjectNotes/1.HTMLandCSSnotes/:splat"
  status = 200
