[build]
  publish = "."
  command = "echo 'no build script'"

[[redirects]]
  from = "public/2.ProjectNotes/1.HTMLandCSSnotes/*"
  to = "public/1.Portfolio/:splat"
  status = 301
  force = true
